#!/usr/bin/env bash
#while loop + if statement

count=1
while [ $count -le 10 ]; do
        if [ $count -eq 9 ]; then
         echo -e "Best School\nHi"
        else
         echo "Best School"
        fi
        ((count++))
done
