#!/usr/bin/env bash
#if statement

file="school"

#check if file exist
if [ -e "$file" ]; then
	echo "school file exists"

#check if the file is empty
if [ ! -s "$ffile" ]; then
	echo "school file is empty"

else
	echo "school file is not empty"
fi

#check if regular file
if [ -f "$file" ]; then
	echo "school is a regular file"
fi

else
	echo "school does not exist"
fi
