#!/usr/bin/env bash
#if statement

file="school"
# Check if regular file
if [ -f "$file" ]; then
    echo "school is a regular file"
fi

# Check if file exists
if [ -e "$file" ]; then
    echo "school file exists"
else
    echo "school file does not exist"
fi

# Check if file is empty or not
if [ -e "$file" ]; then
    if [ -s "$file" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
fi
