#!/usr/bin/env bash
# Stop the 4-to_infinity_and_beyond script

for pid in /proc/[0-9]*; do
    cmd=$(tr '\0' ' ' < "$pid/cmdline" 2>/dev/null)
    if [[ $cmd == *"/4-to_infinity_and_beyond"* ]]; then
        # Close its stdin to terminate the process
        exec 3> "$pid/fd/0" 2>/dev/null
        exec 3>&- 2>/dev/null
    fi
done
